### ISSUE TITLE
Enchantment Table dont Work

### ISSUE THREAD

**Issue by ZombieGaminqLP** [Jikoo/EnchantableBlocks#10] opened 2019-11-14 14:23 UTC
When Users in Survival put a Furnace in the Enchant table its show enchants when he add Lapis
the enchant gone and he cant select a enchant

Creative Work

Permissions added

**Comment by Jikoo** [comment] 2019-11-14 20:36
Duplicate of #6

**Closed by Jikoo** 2019-11-14 20:36 UTC
