### ISSUE TITLE
Raw ores does not work with fortune

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [Jikoo/EnchantableBlocks#51] opened 2022-03-25 20:30 UTC
I have problem on 1.18.2 with 3.1.1 and 3.1.2-SNAPSHOTb[115](https://ci.appveyor.com/project/Jikoo/enchantableblocks/builds/42872287) that raw ores are not beeing processed by fortune

**Comment by Jikoo** [comment] 2022-03-25 20:39
Duplicate of #43

**Closed by Jikoo** 2022-03-25 20:39 UTC
